### PR TITLE
Migrated to View binding

### PR DESCRIPTION
**Pull request by rohithThammaiah**
While working on the **Compose News Detail** screen Kotlin `1.4.10` was giving errors about Kotlin synthetic. So I had to resort to ViewBindings or wait until Kotlin `1.4.20`(https://issuetracker.google.com/issues/166927559).

### CODE REVIEW

**Comment by rohithThammaiah** [comment]
`* Where:
Build file '/home/runner/work/News/News/app/build.gradle' line: 21
 `
Breaks during the assignment of value to `NEWS_API_KEY`

**Comment by iNoles** [comment]
I think it is best to do View Binding because kotlin android extensions actually deprecated. https://youtrack.jetbrains.com/issue/KT-42121

**Comment by AkshayChordiya** [comment]
@rohithThammaiah Don't worry about the error on CI. It's an limitation of GitHub action where forks don't have access to the secrets which causes them fail.
I have been looking for workarounds / solutions for quite some time now 😞

**Review by AkshayChordiya — APPROVED** [review]
Sweet 🤝

**Pull request merged**
